// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesperinterchain/collateral/v1/collateral_type.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CollateralType defines the CollateralType message.
type CollateralType struct {
	Denom              string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Decimals           int64  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	LiquidationRatio   string `protobuf:"bytes,4,opt,name=liquidation_ratio,json=liquidationRatio,proto3" json:"liquidation_ratio,omitempty"`
	MintingRatio       string `protobuf:"bytes,5,opt,name=minting_ratio,json=mintingRatio,proto3" json:"minting_ratio,omitempty"`
	StabilityFee       string `protobuf:"bytes,6,opt,name=stability_fee,json=stabilityFee,proto3" json:"stability_fee,omitempty"`
	LiquidationPenalty string `protobuf:"bytes,7,opt,name=liquidation_penalty,json=liquidationPenalty,proto3" json:"liquidation_penalty,omitempty"`
	Enabled            bool   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *CollateralType) Reset()         { *m = CollateralType{} }
func (m *CollateralType) String() string { return proto.CompactTextString(m) }
func (*CollateralType) ProtoMessage()    {}
func (*CollateralType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77d8f44f30f6f6e, []int{0}
}
func (m *CollateralType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollateralType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollateralType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollateralType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollateralType.Merge(m, src)
}
func (m *CollateralType) XXX_Size() int {
	return m.Size()
}
func (m *CollateralType) XXX_DiscardUnknown() {
	xxx_messageInfo_CollateralType.DiscardUnknown(m)
}

var xxx_messageInfo_CollateralType proto.InternalMessageInfo

func (m *CollateralType) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *CollateralType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollateralType) GetDecimals() int64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *CollateralType) GetLiquidationRatio() string {
	if m != nil {
		return m.LiquidationRatio
	}
	return ""
}

func (m *CollateralType) GetMintingRatio() string {
	if m != nil {
		return m.MintingRatio
	}
	return ""
}

func (m *CollateralType) GetStabilityFee() string {
	if m != nil {
		return m.StabilityFee
	}
	return ""
}

func (m *CollateralType) GetLiquidationPenalty() string {
	if m != nil {
		return m.LiquidationPenalty
	}
	return ""
}

func (m *CollateralType) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*CollateralType)(nil), "vesperinterchain.collateral.v1.CollateralType")
}

func init() {
	proto.RegisterFile("vesperinterchain/collateral/v1/collateral_type.proto", fileDescriptor_d77d8f44f30f6f6e)
}

var fileDescriptor_d77d8f44f30f6f6e = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0xc5, 0x9b, 0xfe, 0xff, 0xc2, 0xa7, 0x68, 0x74, 0x11, 0x5c, 0x84, 0xa2, 0x9b, 0x82, 0x74,
	0x86, 0xa2, 0x2f, 0xa0, 0x82, 0xe0, 0x4e, 0x06, 0x71, 0xa1, 0x8b, 0x92, 0x99, 0xb9, 0xb6, 0x81,
	0x4c, 0x32, 0xce, 0xa4, 0xc5, 0x79, 0x0b, 0x97, 0x3e, 0x92, 0xcb, 0x2e, 0x5d, 0x4a, 0xe7, 0x45,
	0x64, 0x32, 0x75, 0x1a, 0xdc, 0x24, 0x39, 0xe7, 0xfc, 0x2e, 0x81, 0x7b, 0xf0, 0xe5, 0x0a, 0xf2,
	0x14, 0x32, 0xa1, 0x0c, 0x64, 0xd1, 0x82, 0x0b, 0xe5, 0x47, 0x5a, 0x4a, 0x6e, 0x20, 0xe3, 0xd2,
	0x5f, 0x4d, 0x1d, 0x35, 0x33, 0x45, 0x0a, 0x5e, 0x9a, 0x69, 0xa3, 0x09, 0xfb, 0x3b, 0xe5, 0xed,
	0x38, 0x6f, 0x35, 0x3d, 0xfd, 0x68, 0xe3, 0xfd, 0x9b, 0xc6, 0x79, 0x28, 0x52, 0x20, 0xc7, 0xb8,
	0x17, 0x83, 0xd2, 0x09, 0x45, 0x23, 0x34, 0xfe, 0x17, 0xd4, 0x82, 0x10, 0xdc, 0x55, 0x3c, 0x01,
	0xda, 0xb6, 0xa6, 0x7d, 0x93, 0x13, 0x3c, 0x8c, 0x21, 0x12, 0x09, 0x97, 0x39, 0xed, 0x8c, 0xd0,
	0xb8, 0x13, 0x34, 0x9a, 0x9c, 0xe3, 0x43, 0x29, 0x5e, 0x97, 0x22, 0xe6, 0x46, 0x68, 0x35, 0xcb,
	0xaa, 0x8b, 0x76, 0xed, 0xf0, 0x81, 0x13, 0x04, 0xd5, 0x49, 0xce, 0xf0, 0x5e, 0x22, 0x94, 0x11,
	0x6a, 0xbe, 0x05, 0x7b, 0x16, 0xfc, 0xbf, 0x35, 0x1b, 0x28, 0x37, 0x3c, 0x14, 0x52, 0x98, 0x62,
	0xf6, 0x02, 0x40, 0xfb, 0x35, 0xd4, 0x98, 0xb7, 0x00, 0xc4, 0xc7, 0x47, 0xee, 0xb7, 0x29, 0x28,
	0x2e, 0x4d, 0x41, 0x07, 0x16, 0x25, 0x4e, 0x74, 0x5f, 0x27, 0x84, 0xe2, 0x01, 0x28, 0x1e, 0x4a,
	0x88, 0xe9, 0x70, 0x84, 0xc6, 0xc3, 0xe0, 0x57, 0x5e, 0x3f, 0x7f, 0x6e, 0x18, 0x5a, 0x6f, 0x18,
	0xfa, 0xde, 0x30, 0xf4, 0x5e, 0xb2, 0xd6, 0xba, 0x64, 0xad, 0xaf, 0x92, 0xb5, 0x9e, 0xae, 0xe6,
	0xc2, 0x2c, 0x96, 0xa1, 0x17, 0xe9, 0xc4, 0x7f, 0xb4, 0xfb, 0x9d, 0xdc, 0xed, 0x6a, 0xa9, 0x37,
	0x3e, 0x71, 0x8a, 0x7a, 0x73, 0xab, 0xaa, 0xca, 0xc9, 0xc3, 0xbe, 0xad, 0xe7, 0xe2, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x46, 0xc7, 0x05, 0xfa, 0xd6, 0x01, 0x00, 0x00,
}

func (m *CollateralType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollateralType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollateralType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.LiquidationPenalty) > 0 {
		i -= len(m.LiquidationPenalty)
		copy(dAtA[i:], m.LiquidationPenalty)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.LiquidationPenalty)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.StabilityFee) > 0 {
		i -= len(m.StabilityFee)
		copy(dAtA[i:], m.StabilityFee)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.StabilityFee)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MintingRatio) > 0 {
		i -= len(m.MintingRatio)
		copy(dAtA[i:], m.MintingRatio)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.MintingRatio)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LiquidationRatio) > 0 {
		i -= len(m.LiquidationRatio)
		copy(dAtA[i:], m.LiquidationRatio)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.LiquidationRatio)))
		i--
		dAtA[i] = 0x22
	}
	if m.Decimals != 0 {
		i = encodeVarintCollateralType(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCollateralType(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCollateralType(dAtA []byte, offset int, v uint64) int {
	offset -= sovCollateralType(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CollateralType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovCollateralType(uint64(m.Decimals))
	}
	l = len(m.LiquidationRatio)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	l = len(m.MintingRatio)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	l = len(m.StabilityFee)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	l = len(m.LiquidationPenalty)
	if l > 0 {
		n += 1 + l + sovCollateralType(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func sovCollateralType(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCollateralType(x uint64) (n int) {
	return sovCollateralType(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CollateralType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollateralType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollateralType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollateralType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintingRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StabilityFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StabilityFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPenalty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateralType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateralType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationPenalty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCollateralType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollateralType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCollateralType(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCollateralType
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateralType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCollateralType
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCollateralType
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCollateralType
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCollateralType        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCollateralType          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCollateralType = fmt.Errorf("proto: unexpected end of group")
)
