// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesperinterchain/collateral/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// liquidation_ratio is the minimum collateral ratio (e.g., 1.5 = 150%)
	LiquidationRatio string `protobuf:"bytes,1,opt,name=liquidation_ratio,json=liquidationRatio,proto3" json:"liquidation_ratio,omitempty"`
	// liquidation_penalty is the penalty for liquidators (e.g., 0.05 = 5%)
	LiquidationPenalty string `protobuf:"bytes,2,opt,name=liquidation_penalty,json=liquidationPenalty,proto3" json:"liquidation_penalty,omitempty"`
	// min_collateral_amount is the minimum deposit amount
	MinCollateralAmount string `protobuf:"bytes,3,opt,name=min_collateral_amount,json=minCollateralAmount,proto3" json:"min_collateral_amount,omitempty"`
	// supported_collateral_denom is the only collateral accepted
	SupportedCollateralDenom string `protobuf:"bytes,4,opt,name=supported_collateral_denom,json=supportedCollateralDenom,proto3" json:"supported_collateral_denom,omitempty"`
	// max_loan_to_value is the maximum mintable vs collateral value (e.g., 0.8 = 80%)
	MaxLoanToValue string `protobuf:"bytes,5,opt,name=max_loan_to_value,json=maxLoanToValue,proto3" json:"max_loan_to_value,omitempty"`
	// min_debt_amount is the minimum debt amount (prevents dust)
	MinDebtAmount string `protobuf:"bytes,6,opt,name=min_debt_amount,json=minDebtAmount,proto3" json:"min_debt_amount,omitempty"`
	// oracle_price_stale_seconds is the max age of oracle price
	OraclePriceStaleSeconds int64 `protobuf:"varint,7,opt,name=oracle_price_stale_seconds,json=oraclePriceStaleSeconds,proto3" json:"oracle_price_stale_seconds,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_808bb58791681419, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLiquidationRatio() string {
	if m != nil {
		return m.LiquidationRatio
	}
	return ""
}

func (m *Params) GetLiquidationPenalty() string {
	if m != nil {
		return m.LiquidationPenalty
	}
	return ""
}

func (m *Params) GetMinCollateralAmount() string {
	if m != nil {
		return m.MinCollateralAmount
	}
	return ""
}

func (m *Params) GetSupportedCollateralDenom() string {
	if m != nil {
		return m.SupportedCollateralDenom
	}
	return ""
}

func (m *Params) GetMaxLoanToValue() string {
	if m != nil {
		return m.MaxLoanToValue
	}
	return ""
}

func (m *Params) GetMinDebtAmount() string {
	if m != nil {
		return m.MinDebtAmount
	}
	return ""
}

func (m *Params) GetOraclePriceStaleSeconds() int64 {
	if m != nil {
		return m.OraclePriceStaleSeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "vesperinterchain.collateral.v1.Params")
}

func init() {
	proto.RegisterFile("vesperinterchain/collateral/v1/params.proto", fileDescriptor_808bb58791681419)
}

var fileDescriptor_808bb58791681419 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x8b, 0x14, 0x31,
	0x18, 0xc6, 0x77, 0x5c, 0x5d, 0x31, 0xe0, 0x9f, 0xcd, 0x29, 0x0e, 0x53, 0x8c, 0x87, 0x88, 0x9c,
	0x1e, 0x3b, 0xc3, 0x69, 0xa7, 0x36, 0xa7, 0xd7, 0x08, 0x16, 0xcb, 0x9e, 0x5c, 0xa1, 0x45, 0x78,
	0x67, 0x26, 0xec, 0x05, 0x92, 0xbc, 0x31, 0x93, 0x19, 0xf6, 0xbe, 0x82, 0x95, 0x9d, 0xad, 0x1f,
	0xc1, 0x8f, 0x61, 0x79, 0xa5, 0xa5, 0xec, 0x16, 0xfa, 0x31, 0x24, 0x19, 0xdd, 0x19, 0x94, 0x6b,
	0x92, 0x90, 0xdf, 0xef, 0x79, 0x78, 0xe1, 0x25, 0xfb, 0x2d, 0xaf, 0x0d, 0xb7, 0x42, 0x3b, 0x6e,
	0xcb, 0x53, 0x10, 0x3a, 0x2f, 0x51, 0x4a, 0x70, 0xdc, 0x82, 0xcc, 0xdb, 0x83, 0xdc, 0x80, 0x05,
	0x55, 0x67, 0xc6, 0xa2, 0x43, 0x9a, 0xfe, 0x2b, 0x67, 0xbd, 0x9c, 0xb5, 0x07, 0xc9, 0x14, 0x94,
	0xd0, 0x98, 0x87, 0xb3, 0x8b, 0x24, 0xb7, 0x97, 0xb8, 0xc4, 0xf0, 0xcc, 0xfd, 0xab, 0xfb, 0xbd,
	0xff, 0x79, 0x4c, 0x26, 0xf3, 0xd0, 0x4c, 0xf7, 0xc9, 0x54, 0x8a, 0x0f, 0x8d, 0xa8, 0xc0, 0x09,
	0xd4, 0xcc, 0xfa, 0x2b, 0x8e, 0x76, 0xa3, 0xbd, 0x6b, 0x8b, 0x5b, 0x03, 0xb0, 0xf0, 0x27, 0xcd,
	0xc9, 0xce, 0x50, 0x36, 0x5c, 0x83, 0x74, 0x67, 0xf1, 0xa5, 0xa0, 0xd3, 0x01, 0x9a, 0x77, 0x84,
	0x3e, 0x21, 0x77, 0x94, 0xd0, 0xac, 0x1f, 0x93, 0x81, 0xc2, 0x46, 0xbb, 0x78, 0x1c, 0x22, 0x3b,
	0x4a, 0xe8, 0x57, 0x5b, 0x76, 0x18, 0x10, 0x7d, 0x41, 0x92, 0xba, 0x31, 0x06, 0xad, 0xe3, 0xd5,
	0x30, 0x59, 0x71, 0x8d, 0x2a, 0xbe, 0x1c, 0x82, 0xf1, 0xd6, 0xe8, 0xe3, 0x47, 0x9e, 0xd3, 0x47,
	0x64, 0xaa, 0x60, 0xc5, 0x24, 0x82, 0x66, 0x0e, 0x59, 0x0b, 0xb2, 0xe1, 0xf1, 0x95, 0x10, 0xba,
	0xa1, 0x60, 0xf5, 0x06, 0x41, 0xbf, 0xc5, 0x13, 0xff, 0x4b, 0x1f, 0x92, 0x9b, 0x7e, 0xb8, 0x8a,
	0x17, 0xee, 0xef, 0x58, 0x93, 0x20, 0x5e, 0x57, 0x42, 0x1f, 0xf1, 0xc2, 0xfd, 0x19, 0xe8, 0x39,
	0x49, 0xd0, 0x42, 0x29, 0x39, 0x33, 0x56, 0x94, 0x9c, 0xd5, 0x0e, 0x24, 0x67, 0x35, 0x2f, 0x51,
	0x57, 0x75, 0x7c, 0x75, 0x37, 0xda, 0x1b, 0x2f, 0xee, 0x76, 0xc6, 0xdc, 0x0b, 0xc7, 0x9e, 0x1f,
	0x77, 0xf8, 0xd9, 0xec, 0xd7, 0x97, 0x7b, 0xd1, 0xc7, 0x9f, 0x5f, 0x1f, 0x3f, 0xf8, 0x6f, 0xd3,
	0xab, 0xe1, 0xae, 0xbb, 0x75, 0xbc, 0x7c, 0xff, 0x6d, 0x9d, 0x46, 0xe7, 0xeb, 0x34, 0xfa, 0xb1,
	0x4e, 0xa3, 0x4f, 0x9b, 0x74, 0x74, 0xbe, 0x49, 0x47, 0xdf, 0x37, 0xe9, 0xe8, 0xdd, 0xe1, 0x52,
	0xb8, 0xd3, 0xa6, 0xc8, 0x4a, 0x54, 0xf9, 0x49, 0xa8, 0x9a, 0xbd, 0xee, 0xbb, 0xba, 0xf2, 0xd9,
	0x45, 0xed, 0xee, 0xcc, 0xf0, 0xba, 0x98, 0x84, 0xed, 0x3f, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x3a, 0x91, 0x8b, 0x75, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LiquidationRatio != that1.LiquidationRatio {
		return false
	}
	if this.LiquidationPenalty != that1.LiquidationPenalty {
		return false
	}
	if this.MinCollateralAmount != that1.MinCollateralAmount {
		return false
	}
	if this.SupportedCollateralDenom != that1.SupportedCollateralDenom {
		return false
	}
	if this.MaxLoanToValue != that1.MaxLoanToValue {
		return false
	}
	if this.MinDebtAmount != that1.MinDebtAmount {
		return false
	}
	if this.OraclePriceStaleSeconds != that1.OraclePriceStaleSeconds {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OraclePriceStaleSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OraclePriceStaleSeconds))
		i--
		dAtA[i] = 0x38
	}
	if len(m.MinDebtAmount) > 0 {
		i -= len(m.MinDebtAmount)
		copy(dAtA[i:], m.MinDebtAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinDebtAmount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.MaxLoanToValue) > 0 {
		i -= len(m.MaxLoanToValue)
		copy(dAtA[i:], m.MaxLoanToValue)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MaxLoanToValue)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SupportedCollateralDenom) > 0 {
		i -= len(m.SupportedCollateralDenom)
		copy(dAtA[i:], m.SupportedCollateralDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SupportedCollateralDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MinCollateralAmount) > 0 {
		i -= len(m.MinCollateralAmount)
		copy(dAtA[i:], m.MinCollateralAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinCollateralAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LiquidationPenalty) > 0 {
		i -= len(m.LiquidationPenalty)
		copy(dAtA[i:], m.LiquidationPenalty)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LiquidationPenalty)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.LiquidationRatio) > 0 {
		i -= len(m.LiquidationRatio)
		copy(dAtA[i:], m.LiquidationRatio)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LiquidationRatio)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LiquidationRatio)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.LiquidationPenalty)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MinCollateralAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.SupportedCollateralDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MaxLoanToValue)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MinDebtAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.OraclePriceStaleSeconds != 0 {
		n += 1 + sovParams(uint64(m.OraclePriceStaleSeconds))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPenalty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationPenalty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedCollateralDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedCollateralDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLoanToValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxLoanToValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDebtAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinDebtAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePriceStaleSeconds", wireType)
			}
			m.OraclePriceStaleSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OraclePriceStaleSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
