// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesperinterchain/collateral/v1/vault.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Vault defines the Vault message.
type Vault struct {
	CollateralType   string `protobuf:"bytes,1,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty"`
	TotalCollateral  string `protobuf:"bytes,2,opt,name=total_collateral,json=totalCollateral,proto3" json:"total_collateral,omitempty"`
	TotalDebt        string `protobuf:"bytes,3,opt,name=total_debt,json=totalDebt,proto3" json:"total_debt,omitempty"`
	UtilizationRatio string `protobuf:"bytes,4,opt,name=utilization_ratio,json=utilizationRatio,proto3" json:"utilization_ratio,omitempty"`
	DebtCeiling      string `protobuf:"bytes,5,opt,name=debt_ceiling,json=debtCeiling,proto3" json:"debt_ceiling,omitempty"`
	LastUpdated      int64  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_419e662bfa91d113, []int{0}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetCollateralType() string {
	if m != nil {
		return m.CollateralType
	}
	return ""
}

func (m *Vault) GetTotalCollateral() string {
	if m != nil {
		return m.TotalCollateral
	}
	return ""
}

func (m *Vault) GetTotalDebt() string {
	if m != nil {
		return m.TotalDebt
	}
	return ""
}

func (m *Vault) GetUtilizationRatio() string {
	if m != nil {
		return m.UtilizationRatio
	}
	return ""
}

func (m *Vault) GetDebtCeiling() string {
	if m != nil {
		return m.DebtCeiling
	}
	return ""
}

func (m *Vault) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func init() {
	proto.RegisterType((*Vault)(nil), "vesperinterchain.collateral.v1.Vault")
}

func init() {
	proto.RegisterFile("vesperinterchain/collateral/v1/vault.proto", fileDescriptor_419e662bfa91d113)
}

var fileDescriptor_419e662bfa91d113 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x18, 0x46, 0x6b, 0x4a, 0x2b, 0xd5, 0x45, 0xb4, 0x78, 0xf2, 0x82, 0x55, 0x58, 0x28, 0xa0, 0x26,
	0xaa, 0x38, 0x01, 0x94, 0x85, 0x35, 0x82, 0x0e, 0x30, 0x44, 0x4e, 0x62, 0xb5, 0x96, 0x4c, 0x1c,
	0x25, 0x7f, 0x22, 0xca, 0x29, 0x38, 0x16, 0x63, 0x47, 0x46, 0x94, 0xcc, 0xdc, 0x01, 0xd9, 0x91,
	0x70, 0xc4, 0x62, 0x4b, 0xef, 0x7b, 0xfa, 0x87, 0x87, 0xaf, 0x2a, 0x51, 0x64, 0x22, 0x97, 0x29,
	0x88, 0x3c, 0xde, 0x72, 0x99, 0xfa, 0xb1, 0x56, 0x8a, 0x83, 0xc8, 0xb9, 0xf2, 0xab, 0xa5, 0x5f,
	0xf1, 0x52, 0x81, 0x97, 0xe5, 0x1a, 0x34, 0x61, 0xff, 0x5d, 0xcf, 0xb9, 0x5e, 0xb5, 0x3c, 0xff,
	0x41, 0x78, 0xb0, 0x36, 0x3e, 0xb9, 0xc0, 0x13, 0x37, 0x85, 0xb0, 0xcb, 0x04, 0x45, 0x33, 0x34,
	0x1f, 0x05, 0xc7, 0x0e, 0x3f, 0xee, 0x32, 0x41, 0x2e, 0xf1, 0x14, 0x34, 0x70, 0x15, 0x3a, 0x4e,
	0x0f, 0xac, 0x39, 0xb1, 0x7c, 0xf5, 0x87, 0xc9, 0x29, 0xc6, 0xad, 0x9a, 0x88, 0x08, 0x68, 0xdf,
	0x4a, 0x23, 0x4b, 0xee, 0x45, 0x04, 0xe4, 0x1a, 0x9f, 0x94, 0x20, 0x95, 0x7c, 0xe7, 0x20, 0x75,
	0x1a, 0xe6, 0xe6, 0xa3, 0x87, 0xd6, 0x9a, 0x76, 0x86, 0xc0, 0xbc, 0xe4, 0x0c, 0x1f, 0x99, 0x2b,
	0x61, 0x2c, 0xa4, 0x92, 0xe9, 0x86, 0x0e, 0xac, 0x37, 0x36, 0x6c, 0xd5, 0x22, 0xa3, 0x28, 0x5e,
	0x40, 0x58, 0x66, 0x09, 0x07, 0x91, 0xd0, 0xe1, 0x0c, 0xcd, 0xfb, 0xc1, 0xd8, 0xb0, 0xa7, 0x16,
	0xdd, 0xbd, 0x7c, 0xd6, 0x0c, 0xed, 0x6b, 0x86, 0xbe, 0x6b, 0x86, 0x3e, 0x1a, 0xd6, 0xdb, 0x37,
	0xac, 0xf7, 0xd5, 0xb0, 0xde, 0xf3, 0xed, 0x46, 0xc2, 0xb6, 0x8c, 0xbc, 0x58, 0xbf, 0xfa, 0x6b,
	0x1b, 0x6d, 0xf1, 0xe0, 0x0a, 0xb7, 0x19, 0x17, 0x9d, 0xe6, 0x6f, 0xdd, 0xea, 0x26, 0x57, 0x11,
	0x0d, 0x6d, 0xf3, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x59, 0x6b, 0xd6, 0xa1, 0x01,
	0x00, 0x00,
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdated != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.LastUpdated))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DebtCeiling) > 0 {
		i -= len(m.DebtCeiling)
		copy(dAtA[i:], m.DebtCeiling)
		i = encodeVarintVault(dAtA, i, uint64(len(m.DebtCeiling)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.UtilizationRatio) > 0 {
		i -= len(m.UtilizationRatio)
		copy(dAtA[i:], m.UtilizationRatio)
		i = encodeVarintVault(dAtA, i, uint64(len(m.UtilizationRatio)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TotalDebt) > 0 {
		i -= len(m.TotalDebt)
		copy(dAtA[i:], m.TotalDebt)
		i = encodeVarintVault(dAtA, i, uint64(len(m.TotalDebt)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TotalCollateral) > 0 {
		i -= len(m.TotalCollateral)
		copy(dAtA[i:], m.TotalCollateral)
		i = encodeVarintVault(dAtA, i, uint64(len(m.TotalCollateral)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CollateralType) > 0 {
		i -= len(m.CollateralType)
		copy(dAtA[i:], m.CollateralType)
		i = encodeVarintVault(dAtA, i, uint64(len(m.CollateralType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollateralType)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.TotalCollateral)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.TotalDebt)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.UtilizationRatio)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.DebtCeiling)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if m.LastUpdated != 0 {
		n += 1 + sovVault(uint64(m.LastUpdated))
	}
	return n
}

func sovVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVault(x uint64) (n int) {
	return sovVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCollateral", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalCollateral = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalDebt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UtilizationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UtilizationRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtCeiling", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DebtCeiling = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			m.LastUpdated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdated |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVault = fmt.Errorf("proto: unexpected end of group")
)
