// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesperinterchain/liquidation/v1/liquidation_queue.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LiquidationQueue defines the LiquidationQueue message.
type LiquidationQueue struct {
	PositionId       uint64 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Owner            string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CollateralType   string `protobuf:"bytes,3,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty"`
	CollateralAmount string `protobuf:"bytes,4,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`
	DebtAmount       string `protobuf:"bytes,5,opt,name=debt_amount,json=debtAmount,proto3" json:"debt_amount,omitempty"`
	HealthFactor     string `protobuf:"bytes,6,opt,name=health_factor,json=healthFactor,proto3" json:"health_factor,omitempty"`
	Timestamp        int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status           string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *LiquidationQueue) Reset()         { *m = LiquidationQueue{} }
func (m *LiquidationQueue) String() string { return proto.CompactTextString(m) }
func (*LiquidationQueue) ProtoMessage()    {}
func (*LiquidationQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3809bc568be5fce5, []int{0}
}
func (m *LiquidationQueue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidationQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidationQueue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidationQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationQueue.Merge(m, src)
}
func (m *LiquidationQueue) XXX_Size() int {
	return m.Size()
}
func (m *LiquidationQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationQueue.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationQueue proto.InternalMessageInfo

func (m *LiquidationQueue) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *LiquidationQueue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LiquidationQueue) GetCollateralType() string {
	if m != nil {
		return m.CollateralType
	}
	return ""
}

func (m *LiquidationQueue) GetCollateralAmount() string {
	if m != nil {
		return m.CollateralAmount
	}
	return ""
}

func (m *LiquidationQueue) GetDebtAmount() string {
	if m != nil {
		return m.DebtAmount
	}
	return ""
}

func (m *LiquidationQueue) GetHealthFactor() string {
	if m != nil {
		return m.HealthFactor
	}
	return ""
}

func (m *LiquidationQueue) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LiquidationQueue) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*LiquidationQueue)(nil), "vesperinterchain.liquidation.v1.LiquidationQueue")
}

func init() {
	proto.RegisterFile("vesperinterchain/liquidation/v1/liquidation_queue.proto", fileDescriptor_3809bc568be5fce5)
}

var fileDescriptor_3809bc568be5fce5 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x3b, 0xfd, 0xfb, 0xbe, 0x8e, 0x7f, 0x75, 0x10, 0x99, 0x85, 0xa4, 0x45, 0x17, 0x16,
	0xa4, 0x29, 0xc5, 0x85, 0x6b, 0xbb, 0x10, 0x0a, 0x6e, 0x2c, 0xe2, 0x42, 0x84, 0x32, 0x4d, 0x8e,
	0x66, 0x20, 0xc9, 0xa4, 0x99, 0x33, 0xd5, 0xde, 0x85, 0x7b, 0x6f, 0xc8, 0x65, 0x97, 0x2e, 0xa5,
	0xbd, 0x11, 0xc9, 0xb4, 0x25, 0xd1, 0xe5, 0x79, 0xce, 0x73, 0x86, 0xe1, 0x7d, 0xe9, 0xd5, 0x0c,
	0x74, 0x02, 0xa9, 0x8c, 0x11, 0x52, 0x2f, 0x10, 0x32, 0xee, 0x85, 0x72, 0x6a, 0xa4, 0x2f, 0x50,
	0xaa, 0xb8, 0x37, 0xeb, 0x17, 0xc7, 0xf1, 0xd4, 0x80, 0x01, 0x37, 0x49, 0x15, 0x2a, 0xd6, 0xfa,
	0x7b, 0xe8, 0x16, 0x4c, 0x77, 0xd6, 0x3f, 0xfd, 0x28, 0xd3, 0xe6, 0x6d, 0x8e, 0xee, 0xb2, 0x5b,
	0xd6, 0xa2, 0x3b, 0x89, 0xd2, 0xd2, 0xbe, 0x26, 0x7d, 0x4e, 0xda, 0xa4, 0x53, 0x1d, 0xd1, 0x2d,
	0x1a, 0xfa, 0xec, 0x88, 0xd6, 0xd4, 0x6b, 0x0c, 0x29, 0x2f, 0xb7, 0x49, 0xa7, 0x31, 0x5a, 0x0f,
	0xec, 0x9c, 0x1e, 0x78, 0x2a, 0x0c, 0x05, 0x42, 0x2a, 0xc2, 0x31, 0xce, 0x13, 0xe0, 0x15, 0xbb,
	0xdf, 0xcf, 0xf1, 0xfd, 0x3c, 0x01, 0x76, 0x41, 0x0f, 0x0b, 0xa2, 0x88, 0x94, 0x89, 0x91, 0x57,
	0xad, 0xda, 0xcc, 0x17, 0xd7, 0x96, 0x67, 0x9f, 0xf1, 0x61, 0x82, 0x5b, 0xad, 0x66, 0x35, 0x9a,
	0xa1, 0x8d, 0x70, 0x46, 0xf7, 0x02, 0x10, 0x21, 0x06, 0xe3, 0x67, 0xe1, 0xa1, 0x4a, 0x79, 0xdd,
	0x2a, 0xbb, 0x6b, 0x78, 0x63, 0x19, 0x3b, 0xa1, 0x0d, 0x94, 0x11, 0x68, 0x14, 0x51, 0xc2, 0xff,
	0xb5, 0x49, 0xa7, 0x32, 0xca, 0x01, 0x3b, 0xa6, 0x75, 0x8d, 0x02, 0x8d, 0xe6, 0xff, 0xed, 0xed,
	0x66, 0x1a, 0x3c, 0x7d, 0x2e, 0x1d, 0xb2, 0x58, 0x3a, 0xe4, 0x7b, 0xe9, 0x90, 0xf7, 0x95, 0x53,
	0x5a, 0xac, 0x9c, 0xd2, 0xd7, 0xca, 0x29, 0x3d, 0x0e, 0x5e, 0x24, 0x06, 0x66, 0xe2, 0x7a, 0x2a,
	0xea, 0x3d, 0xd8, 0x8c, 0xbb, 0xc3, 0xbc, 0x9d, 0x75, 0xea, 0xdd, 0x42, 0x5f, 0x6f, 0xbf, 0x1a,
	0xcb, 0xb2, 0xd1, 0x93, 0xba, 0xed, 0xe8, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x8d, 0x5f,
	0xde, 0xde, 0x01, 0x00, 0x00,
}

func (m *LiquidationQueue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidationQueue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidationQueue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x42
	}
	if m.Timestamp != 0 {
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x38
	}
	if len(m.HealthFactor) > 0 {
		i -= len(m.HealthFactor)
		copy(dAtA[i:], m.HealthFactor)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.HealthFactor)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DebtAmount) > 0 {
		i -= len(m.DebtAmount)
		copy(dAtA[i:], m.DebtAmount)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.DebtAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CollateralAmount) > 0 {
		i -= len(m.CollateralAmount)
		copy(dAtA[i:], m.CollateralAmount)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.CollateralAmount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CollateralType) > 0 {
		i -= len(m.CollateralType)
		copy(dAtA[i:], m.CollateralType)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.CollateralType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.PositionId != 0 {
		i = encodeVarintLiquidationQueue(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidationQueue(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidationQueue(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidationQueue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovLiquidationQueue(uint64(m.PositionId))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	l = len(m.CollateralType)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	l = len(m.CollateralAmount)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	l = len(m.DebtAmount)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	l = len(m.HealthFactor)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovLiquidationQueue(uint64(m.Timestamp))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovLiquidationQueue(uint64(l))
	}
	return n
}

func sovLiquidationQueue(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidationQueue(x uint64) (n int) {
	return sovLiquidationQueue(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidationQueue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidationQueue
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidationQueue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidationQueue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DebtAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HealthFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HealthFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidationQueue(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidationQueue
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidationQueue(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidationQueue
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidationQueue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidationQueue
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidationQueue
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidationQueue
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidationQueue        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidationQueue          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidationQueue = fmt.Errorf("proto: unexpected end of group")
)
