syntax = "proto3";
package vesperinterchain.vesperinterchain.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "vesperinterchain/vesperinterchain/v1/params.proto";

option go_package = "github.com/Vesper-Interchain/vesper-interchain/x/vesperinterchain/types";

// GenesisState defines the vesperinterchain module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}
