// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesperinterchain/stablecoin/v1/stablecoin_supply.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StablecoinSupply defines the StablecoinSupply message.
type StablecoinSupply struct {
	TotalSupply       string `protobuf:"bytes,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	CirculatingSupply string `protobuf:"bytes,2,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	TreasuryBalance   string `protobuf:"bytes,3,opt,name=treasury_balance,json=treasuryBalance,proto3" json:"treasury_balance,omitempty"`
	LastUpdated       int64  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (m *StablecoinSupply) Reset()         { *m = StablecoinSupply{} }
func (m *StablecoinSupply) String() string { return proto.CompactTextString(m) }
func (*StablecoinSupply) ProtoMessage()    {}
func (*StablecoinSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e97ecd6f75861095, []int{0}
}
func (m *StablecoinSupply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StablecoinSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StablecoinSupply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StablecoinSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StablecoinSupply.Merge(m, src)
}
func (m *StablecoinSupply) XXX_Size() int {
	return m.Size()
}
func (m *StablecoinSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_StablecoinSupply.DiscardUnknown(m)
}

var xxx_messageInfo_StablecoinSupply proto.InternalMessageInfo

func (m *StablecoinSupply) GetTotalSupply() string {
	if m != nil {
		return m.TotalSupply
	}
	return ""
}

func (m *StablecoinSupply) GetCirculatingSupply() string {
	if m != nil {
		return m.CirculatingSupply
	}
	return ""
}

func (m *StablecoinSupply) GetTreasuryBalance() string {
	if m != nil {
		return m.TreasuryBalance
	}
	return ""
}

func (m *StablecoinSupply) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func init() {
	proto.RegisterType((*StablecoinSupply)(nil), "vesperinterchain.stablecoin.v1.StablecoinSupply")
}

func init() {
	proto.RegisterFile("vesperinterchain/stablecoin/v1/stablecoin_supply.proto", fileDescriptor_e97ecd6f75861095)
}

var fileDescriptor_e97ecd6f75861095 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x40, 0x63, 0x8a, 0x90, 0x70, 0x91, 0x28, 0x99, 0x32, 0x59, 0x85, 0xa9, 0x0c, 0x49, 0x54,
	0x21, 0xb1, 0xd3, 0x8d, 0xb5, 0x15, 0x0c, 0x30, 0x44, 0x8e, 0x6b, 0xb5, 0x96, 0x8c, 0x6d, 0xd9,
	0xdf, 0x11, 0xb9, 0x05, 0x67, 0xe1, 0x14, 0x8c, 0x1d, 0x19, 0x51, 0x72, 0x11, 0x54, 0x27, 0xa5,
	0x11, 0xa3, 0x9f, 0xdf, 0xb7, 0xf5, 0x1f, 0xbe, 0xaf, 0xb8, 0x33, 0xdc, 0x0a, 0x05, 0xdc, 0xb2,
	0x2d, 0x15, 0x2a, 0x77, 0x40, 0x4b, 0xc9, 0x99, 0x16, 0x2a, 0xaf, 0xe6, 0x83, 0x53, 0xe1, 0xbc,
	0x31, 0xb2, 0xce, 0x8c, 0xd5, 0xa0, 0x63, 0xf2, 0x7f, 0x2e, 0x3b, 0x9a, 0x59, 0x35, 0xbf, 0xf9,
	0x44, 0x78, 0xb2, 0xfa, 0x23, 0xab, 0x30, 0x1a, 0x5f, 0xe3, 0x0b, 0xd0, 0x40, 0x65, 0xff, 0x54,
	0x82, 0xa6, 0x68, 0x76, 0xbe, 0x1c, 0x07, 0xd6, 0x2b, 0x29, 0x8e, 0x99, 0xb0, 0xcc, 0x4b, 0x0a,
	0x42, 0x6d, 0x0e, 0xe2, 0x49, 0x10, 0xaf, 0x06, 0x37, 0xbd, 0x7e, 0x8b, 0x27, 0x60, 0x39, 0x75,
	0xde, 0xd6, 0x45, 0x49, 0x25, 0x55, 0x8c, 0x27, 0xa3, 0x20, 0x5f, 0x1e, 0xf8, 0xa2, 0xc3, 0xfb,
	0xcf, 0x25, 0x75, 0x50, 0x78, 0xb3, 0xa6, 0xc0, 0xd7, 0xc9, 0xe9, 0x14, 0xcd, 0x46, 0xcb, 0xf1,
	0x9e, 0x3d, 0x75, 0x68, 0xf1, 0xfa, 0xd5, 0x10, 0xb4, 0x6b, 0x08, 0xfa, 0x69, 0x08, 0xfa, 0x68,
	0x49, 0xb4, 0x6b, 0x49, 0xf4, 0xdd, 0x92, 0xe8, 0xe5, 0x61, 0x23, 0x60, 0xeb, 0xcb, 0x8c, 0xe9,
	0xb7, 0xfc, 0x39, 0x6c, 0x9e, 0x3e, 0x1e, 0x93, 0x75, 0x2d, 0xd2, 0x41, 0xc4, 0xf7, 0x61, 0x46,
	0xa8, 0x0d, 0x77, 0xe5, 0x59, 0x08, 0x77, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa6, 0x90,
	0xb4, 0x72, 0x01, 0x00, 0x00,
}

func (m *StablecoinSupply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StablecoinSupply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StablecoinSupply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdated != 0 {
		i = encodeVarintStablecoinSupply(dAtA, i, uint64(m.LastUpdated))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TreasuryBalance) > 0 {
		i -= len(m.TreasuryBalance)
		copy(dAtA[i:], m.TreasuryBalance)
		i = encodeVarintStablecoinSupply(dAtA, i, uint64(len(m.TreasuryBalance)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CirculatingSupply) > 0 {
		i -= len(m.CirculatingSupply)
		copy(dAtA[i:], m.CirculatingSupply)
		i = encodeVarintStablecoinSupply(dAtA, i, uint64(len(m.CirculatingSupply)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TotalSupply) > 0 {
		i -= len(m.TotalSupply)
		copy(dAtA[i:], m.TotalSupply)
		i = encodeVarintStablecoinSupply(dAtA, i, uint64(len(m.TotalSupply)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStablecoinSupply(dAtA []byte, offset int, v uint64) int {
	offset -= sovStablecoinSupply(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StablecoinSupply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TotalSupply)
	if l > 0 {
		n += 1 + l + sovStablecoinSupply(uint64(l))
	}
	l = len(m.CirculatingSupply)
	if l > 0 {
		n += 1 + l + sovStablecoinSupply(uint64(l))
	}
	l = len(m.TreasuryBalance)
	if l > 0 {
		n += 1 + l + sovStablecoinSupply(uint64(l))
	}
	if m.LastUpdated != 0 {
		n += 1 + sovStablecoinSupply(uint64(m.LastUpdated))
	}
	return n
}

func sovStablecoinSupply(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStablecoinSupply(x uint64) (n int) {
	return sovStablecoinSupply(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StablecoinSupply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStablecoinSupply
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StablecoinSupply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StablecoinSupply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CirculatingSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CirculatingSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			m.LastUpdated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdated |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStablecoinSupply(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStablecoinSupply
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStablecoinSupply(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStablecoinSupply
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStablecoinSupply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStablecoinSupply
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStablecoinSupply
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStablecoinSupply
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStablecoinSupply        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStablecoinSupply          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStablecoinSupply = fmt.Errorf("proto: unexpected end of group")
)
