syntax = "proto3";
package vesperinterchain.collateral.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "vesperinterchain/collateral/v1/params.proto";

option go_package = "github.com/Vesper-Interchain/vesper-interchain/x/collateral/types";

// GenesisState defines the collateral module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}
