syntax = "proto3";
package vesperinterchain.collateral.v1;

import "google/api/annotations.proto";
import "vesperinterchain/collateral/v1/position.proto";
import "vesperinterchain/collateral/v1/params.proto";

option go_package = "github.com/Vesper-Interchain/vesper-interchain/x/collateral/types";

service Query {
  rpc Position(QueryPositionRequest) returns (QueryPositionResponse) {
    option (google.api.http).get = "/vesperinterchain/collateral/v1/position/{owner}";
  }

  rpc CollateralRatio(QueryCollateralRatioRequest) returns (QueryCollateralRatioResponse) {
    option (google.api.http).get = "/vesperinterchain/collateral/v1/collateral_ratio/{owner}";
  }

  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/vesperinterchain/collateral/v1/params";
  }
}

message QueryPositionRequest {
  string owner = 1;
}

message QueryPositionResponse {
  Position position = 1;
}

message QueryCollateralRatioRequest {
  string owner = 1;
}

message QueryCollateralRatioResponse {
  string collateral_ratio = 1;
  string collateral_value_usd = 2;
  string debt_value_usd = 3;
}

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1;
}
