syntax = "proto3";

package vesperinterchain.collateral.v1;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "vesperinterchain/collateral/v1/params.proto";

option go_package = "github.com/Vesper-Interchain/vesper-interchain/x/collateral/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // DepositCollateral defines the DepositCollateral RPC.
  rpc DepositCollateral(MsgDepositCollateral) returns (MsgDepositCollateralResponse);

  // WithdrawCollateral defines the WithdrawCollateral RPC.
  rpc WithdrawCollateral(MsgWithdrawCollateral) returns (MsgWithdrawCollateralResponse);

  // MintStablecoin defines the MintStablecoin RPC.
  rpc MintStablecoin(MsgMintStablecoin) returns (MsgMintStablecoinResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "vesperinterchain/x/collateral/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the module parameters to update.

  // NOTE: All parameters must be supplied.
  Params params = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgDepositCollateral defines the MsgDepositCollateral message.
message MsgDepositCollateral {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string denom = 2;
  string amount = 3;
}

// MsgDepositCollateralResponse defines the MsgDepositCollateralResponse message.
message MsgDepositCollateralResponse {}

// MsgWithdrawCollateral defines the MsgWithdrawCollateral message.
message MsgWithdrawCollateral {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  uint64 position_id = 2;
  string amount = 3;
}

// MsgWithdrawCollateralResponse defines the MsgWithdrawCollateralResponse message.
message MsgWithdrawCollateralResponse {}

// MsgMintStablecoin defines the MsgMintStablecoin message.
message MsgMintStablecoin {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  uint64 position_id = 2;
  string amount = 3;
}

// MsgMintStablecoinResponse defines the MsgMintStablecoinResponse message.
message MsgMintStablecoinResponse {}
