syntax = "proto3";

package vesperinterchain.stablecoin.v1;

import "google/api/annotations.proto";
import "vesperinterchain/stablecoin/v1/params.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/Vesper-Interchain/vesper-interchain/x/stablecoin/types";

service Query {
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/vesperinterchain/stablecoin/v1/params";
  }
}

message QueryParamsRequest {}

message QueryParamsResponse {
  Params params = 1 [
    (gogoproto.nullable) = false
  ];
}